# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Nice job here with your seed data!

Neighborhood.destroy_all
Bar.destroy_all

columbia_heights = Neighborhood.create(name: "Columbia Heights", metro_stop: "Columbia Heights", image_url: "neighborhoods/columbia_heights.png")
dupont = Neighborhood.create(name: "Dupont Circle", metro_stop: "Dupont Circle", image_url: "neighborhoods/dupont.png")
u_street = Neighborhood.create(name: "U Street", metro_stop: "U Street", image_url: "neighborhoods/u_street.png")
georgetown = Neighborhood.create(name: "Georgetown", metro_stop: "Foggy Bottom", image_url: "neighborhoods/georgetown.png")
h_street = Neighborhood.create(name: "H Street", image_url: "neighborhoods/h_street.png")
logan_circle = Neighborhood.create(name: "Logan Circle", metro_stop: "Farragut North", image_url: "neighborhoods/logan_circle.png")

meridian_pint = columbia_heights.bars.create(name: "Meridian Pint", category: "Craft Beer", price_meter: "$$", image_url: "bars/meridian_pint.png", description: "Brooklyn cardigan disrupt messenger bag skateboard taxidermy, PBR&B slow-carb migas cliche green juice. Whatever single-origin coffee hashtag, kitsch sriracha thundercats keytar sartorial ennui neutra. Echo park hammock brooklyn ugh pour-over, narwhal authentic fap pickled PBR&B. Ramps gastropub art party kombucha, cred freegan shabby chic farm-to-table. YOLO cronut yr yuccie, before they sold out hella kale chips. Trust fund bicycle rights yr gentrify, lomo meditation taxidermy microdosing post-ironic blue bottle tilde polaroid flannel keffiyeh crucifix. Chicharrones cliche scenester, umami kale chips poutine quinoa four loko freegan disrupt dreamcatcher godard meditation pitchfork.")
sauf_haus = dupont.bars.create(name: "Sauf Haus", category: "Biergarten", price_meter: "$$", image_url: "bars/sauf_haus.png", description: "Brooklyn cardigan disrupt messenger bag skateboard taxidermy, PBR&B slow-carb migas cliche green juice. Whatever single-origin coffee hashtag, kitsch sriracha thundercats keytar sartorial ennui neutra. Echo park hammock brooklyn ugh pour-over, narwhal authentic fap pickled PBR&B. Ramps gastropub art party kombucha, cred freegan shabby chic farm-to-table. YOLO cronut yr yuccie, before they sold out hella kale chips. Trust fund bicycle rights yr gentrify, lomo meditation taxidermy microdosing post-ironic blue bottle tilde polaroid flannel keffiyeh crucifix. Chicharrones cliche scenester, umami kale chips poutine quinoa four loko freegan disrupt dreamcatcher godard meditation pitchfork.")
big_hunt = dupont.bars.create(name: "The Big Hunt", category: "Comedy Club", price_meter: "$", image_url: "bars/the_big_hunt.png", description: "Farm-to-table jean shorts lomo kickstarter trust fund. Ethical pabst distillery, YOLO chia single-origin coffee umami cold-pressed food truck. Umami stumptown humblebrag selvage lo-fi chillwave. Kinfolk tote bag hoodie portland, neutra messenger bag trust fund. Listicle locavore small batch, bicycle rights pork belly retro chillwave gastropub austin sartorial. Fap green juice ugh health goth single-origin coffee kinfolk. Retro 8-bit green juice shoreditch, tousled leggings hella cray.")
ninethirty = u_street.bars.create(name: "The 9:30 Club", category: "Live Music", price_meter: "$$$", image_url: "bars/930club.png", description: "Viral kogi skateboard, pabst literally wayfarers raw denim. Before they sold out blog lumbersexual, chia truffaut vegan fashion axe. Umami venmo XOXO ugh. Pour-over PBR&B brooklyn, hashtag chambray selfies cardigan single-origin coffee gastropub wolf gluten-free DIY microdosing. Art party listicle literally everyday carry mlkshk artisan, squid narwhal. Mlkshk bitters ethical lo-fi, stumptown biodiesel squid celiac irony. Everyday carry etsy cray actually, health goth kogi tofu whatever cardigan polaroid mlkshk try-hard godard hella food truck.")
churchkey = logan_circle.bars.create(name: "Churchkey", category: "Craft Beer", price_meter: "$$", image_url: "bars/churchkey.png", description: "Viral kogi skateboard, pabst literally wayfarers raw denim. Before they sold out blog lumbersexual, chia truffaut vegan fashion axe. Umami venmo XOXO ugh. Pour-over PBR&B brooklyn, hashtag chambray selfies cardigan single-origin coffee gastropub wolf gluten-free DIY microdosing. Art party listicle literally everyday carry mlkshk artisan, squid narwhal. Mlkshk bitters ethical lo-fi, stumptown biodiesel squid celiac irony. Everyday carry etsy cray actually, health goth kogi tofu whatever cardigan polaroid mlkshk try-hard godard hella food truck.")
georgetown_piano = georgetown.bars.create(name: "Georgetown Piano Bar", category: "Live Music", price_meter: "$$", image_url: "bars/georgetown_piano.png", description: "Taxidermy church-key pabst craft beer, knausgaard scenester single-origin coffee VHS neutra authentic pitchfork man bun affogato. Master cleanse health goth fap, everyday carry waistcoat shoreditch banjo hoodie quinoa actually messenger bag. Try-hard humblebrag deep v actually chambray quinoa. Shoreditch art party sustainable keytar kogi organic, umami hella semiotics etsy dreamcatcher flexitarian vice bespoke asymmetrical. Vegan venmo tote bag chartreuse selvage wolf. Blog drinking vinegar gentrify whatever intelligentsia VHS, lo-fi viral pug sartorial banjo hoodie ethical literally. Chartreuse biodiesel venmo XOXO PBR&B, chambray everyday carry vice cold-pressed man bun.")
